### PR TITLE
Path drawing using nodes

### LINKED ISSUE #20: Line support - trail drawing [feature]
Do you plan to support adding a path/line/trail to the map? Is there any timebox during which we can expect functionality to draw a line on the map? The source code contains following lines:

```
/**
 Adds an annotation to the map view.

 @note `MGLMultiPolyline`, `MGLMultiPolygon`, `MGLShapeCollection`, and
    `MGLPointCollection` objects cannot be added to the map view at this time.
    Any multipoint, multipolyline, multipolygon, shape or point collection
    object that is specified is silently ignored.

 @param annotation The annotation object to add to the receiver. This object
    must conform to the `MGLAnnotation` protocol. The map view retains the
    annotation object. */
- (void)addAnnotation:(id <MGLAnnotation>)annotation;
```

[At MapBox blog article](https://blog.mapbox.com/introducing-native-ar-b3c55a50539d) you write:

> The team at Slopes, the iOS app for skiers and snowboarders, used our SceneKit SDK to pull detailed 3D trail guides into their app.

What indicates that either they wrote their custom support for it or it's already in the framework but I can't find it.

Due to it, I'm not sure if there is already support for trails (or at least lines) or we should wait / implement it ourselves / look for a different solution.

### PR DESCRIPTION
**Pull request by natalia-osa**
Fixes #20

Adds possibility to display a route on a selected TerrainNode. Possibilities:
- configure colour
- configure beginning/end sphere radius
- configure line (cylinder) thickness

Also leaves the possibility to simply:
- add a sphere node at a given point
- add a cylinder node at a given point

Things which are not yet done (but I'm planning to do it after my vacations, so after next week):
- calculate distances between points, so it's never bigger than X (eg 5m by default, it'll be configurable). Currently, the user can provide locations array with 2 points and 100 km distance between them, the path will cross through all mountains etc between them. The desired solution will make mid-locations, on which we'll calculate the height and position the cylinders between these. Such way will make the route less likely to go through any obstacles - like a mountain.

### CODE REVIEW

**Comment by camdeardorff** [comment]
This is really cool @natalia-osa, I tried it out and it looks really really good. I have tried testing with some of my own data which is far more dense in terms of points, so many that the path almost looks jagged. This is the problem on the opposite side of what you mentioned had mentioned with too few of points. 

I have been experimenting with reducing the number of points in my path by comparing the distance of the consecutive vectors, not sure if this is a good way of doing so but I thought I might mention it.

**Comment by jim-martin** [comment]
Hi @natalia-osa, thanks for your contribution! 

I've been looking into drawing polylines on a terrainNode and want to share this [experimental branch](https://github.com/mapbox/mapbox-scenekit/tree/jm-line-renderer) that might be what you're looking for in #20.

It minimizes the number of nodes and triangles added to the scene, but requires a physical iOS device to render.  We're still looking at how to distribute the shader files in the MapboxScenekit framework, but have a look at the `DemoPlacementViewController` on that branch the meantime.

**Comment by natalia-osa** [comment]
Hi @jim-martin, thanks for your work, I will check it out during this week and close my PR if your work answers my needs.

It will still need the recalculation of heights periodically, or will it work properly in a scenario where there are too few points and the line goes eg through a mountain? There should be points added in the meantime, so no distance between points is longer than X (eg 2 meters). Otherwise the line in the middle will be going through a wrong height.

**Comment by natalia-osa** [comment]
@jim-martin Hi, could you please update your branch to master? It can't be applied to projects which support pre-iOS 10 versions, like mine. As a result I can neither test nor use it.

**Comment by jim-martin** [comment]
@natalia-osa , I've merged the line drawing branch to master. Let me know how your testing goes!

**Comment by natalia-osa** [comment]
@jim-martin Hi Jim, there are issues with your code after merging. It would be good to have some kind of CI in your framework or merge master to your branch and run it first. The project on master does not compile. There are 8 errors, one is because the inherited method tries to change the accessibility of enclosing type (public -> internal), other 7 are because the new branch is not compatible with iOS 8 and 9, and that compatibility was merged to the master around 2 weeks ago.

I've briefly looked at it and while methods like `UIColor(displayP3Red:green:blue:alpha:)` can be easily replaced with something iOS 8/9 compatible. There is 1 other change not compatible with iOS 9. Other 6 issues are for iOS 8 only. My project needs to support iOS 9, so if you will remove the support for 9, we won't update to any newer library version, unfortunately.

**Comment by natalia-osa** [comment]
@jim-martin Do you +- know when you're going to merge your PR once again and resolve compatibility issues? I'd prefer to use your line drawing, as it's more memory efficient than the one presented here. A simple timebox would be fantastic.

**Comment by natalia-osa** [comment]
To be closed, parts used in #48.

**Pull request closed without merging**
