### PR TITLE
Possibility to multiply height by given value

### PR DESCRIPTION
**Pull request by natalia-osa**
This pull request enables to multiply the height by given constant. Handy when you're drawing a very flat terrain and want it to appear more realistic.

### CODE REVIEW

**Comment by avi-c** [comment]
Hi @natalia-osa 

I'll look at the PR. You are right that something like this is needed in order to improve the visualization for flat terrain. I have used something similar myself but haven't prepared it as a PR, so thank you for your contribution.

**Comment by natalia-osa** [comment]
Should I update this PR to the newest codebase or you don't want to merge it and there's no need to put time into it..?

**Comment by avi-c** [comment]
I think it’s worth adding. Let’s update it and get it merged.

**Review by avi-c — COMMENTED** [review]
In the comments for: the fetchTerrainHeight... function, I think "sharp" is too vague of term to use. I would probably phrase it something like:
- multiplier: Scale factor used to artificially exaggerate or flatten the terrain heights. Useful if you are trying to make an area with relatively flat terrain look for dramatic.

**Comment by natalia-osa** [comment]
@avi-c Changed.

**Review by avi-c — APPROVED** [review]
Looks good.

**Pull request merged**
